### ISSUE TITLE
Error while visualising the calibration results

### ISSUE THREAD

**Issue by abhishekpg111** [oliver-batchelor/multical#52]
Im getting below error while visualising the results. Please help 

home/shashireddy/.local/lib/python3.10/site-packages/pyvista/utilities/helpers.py:507: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(
Traceback (most recent call last):
  File "/home/shashireddy/.local/bin/multical", line 8, in <module>
    sys.exit(cli())
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/app/multical.py", line 28, in cli
    run_with(Multical)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/config/arguments.py", line 73, in run_with
    return program.app.execute()
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/app/multical.py", line 24, in execute
    return self.command.execute()
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/app/calibrate.py", line 21, in execute
    calibrate(self)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/app/calibrate.py", line 44, in calibrate
    visualize_ws(ws)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/app/vis.py", line 32, in visualize_ws
    visualizer.visualize(ws)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/visualizer.py", line 29, in visualize
    vis.update_workspace(workspace)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/visualizer.py", line 206, in update_workspace
    self.update_frame()
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/visualizer.py", line 49, in f
    return func(self, *args, **kwargs)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/visualizer.py", line 54, in f
    return func(self)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/visualizer.py", line 273, in update_frame
    self.update_image()
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/visualizer.py", line 49, in f
    return func(self, *args, **kwargs)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/visualizer.py", line 54, in f
    return func(self)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/visualizer.py", line 300, in update_image
    annotated_image = annotate_image(self.workspace, self.calibration,
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/viewer_image.py", line 150, in annotate_image
    add_reprojections(scene, detections, projected, inliers, workspace.boards, valid_boards, options)
  File "/home/shashireddy/.local/lib/python3.10/site-packages/multical/interface/viewer_image.py", line 104, in add_reprojections
    marker_font.setPixelSize(options.marker_size * 0.75)
TypeError: setPixelSize(self, int): argument 1 has unexpected type 'float'

**Comment by felipe-parodi** [comment]
How did you resolve this? @abhishekpg111

**Comment by Mabroukiimen** [comment]
hello, can you please tell me how did you write the command ?
