### ISSUE TITLE
TypeError issue when attempting to view layer "Detected poses"

### ISSUE THREAD

**Issue by felipe-parodi** [oliver-batchelor/multical#60]
Hello,

thanks for your great work! Whenever i try viewing the "Detected poses" layer in the interface, the software crashes with the following error: 
`Traceback (most recent call last):                                                                        File "C:\ProgramData\Miniconda3\envs\multical2\lib\site-packages\multical\interface\visualizer.py", line 49, in f                                                                                                 return func(self, *args, **kwargs)                                                                    File "C:\ProgramData\Miniconda3\envs\multical2\lib\site-packages\multical\interface\visualizer.py", line 54, in f                                                                                                 return func(self)                                                                                     File "C:\ProgramData\Miniconda3\envs\multical2\lib\site-packages\multical\interface\visualizer.py", line 301, in update_image                                                                                     layer_name, state, options=options)                                                                   File "C:\ProgramData\Miniconda3\envs\multical2\lib\site-packages\multical\interface\viewer_image.py", line 159, in annotate_image                                                                                 points = camera.project(board.points, pose.poses),                                                  TypeError: project() takes 2 positional arguments but 3 were given`. Viewing the other layers works well. Any help? @oliver-batchelor Thanks in advance!

**Comment by felipe-parodi** [comment]
Hi @oliver-batchelor, any ideas on this? thanks for your help.
